name: 'GitOps Automatic Versioning'
author: 'EvilKittenLord'
description: 'Automatically determine semantic version based on branch merge history.'
branding:
  icon: git-branch
  color: white
inputs:
  force-re-evaluate:
    description: "Forces a re-evaluation of the entire git history."
    required: false
    default: 'false'
  force-patch-increment:
    description: "Forces a PATCH increment if no other increment detected. NOTE: This is intended for development purposes only."
    required: false
    default: 'false'
outputs:
  new-version:
    description: "New Version"
    value: ${{ steps.new-version.outputs.new-version }}
  previous-version:
    description: "Previous Version"
    value: ${{ steps.previous-version.outputs.previous-version }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Detect Previous Version
      id: previous-version
      run: |
          cd $GITHUB_WORKSPACE
          echo "previous-version=$(${{ github.action_path }}/scripts/detectPreviousVersion.sh)" | tee $GITHUB_OUTPUT
      shell: bash
    - name: Detect New Version
      id: new-version
      run: |
          cd $GITHUB_WORKSPACE
          opt=''
          [[ "${{ inputs.force-re-evaluate }}" == 'true' ]] && opt='-f'
          [[ "${{ inputs.force-patch-increment }}" == 'true' ]] && opt='-p'
          new_version="$(${{ github.action_path }}/scripts/detectNewVersion.sh $opt)" || true
          echo "new-version=$new_version" | tee $GITHUB_OUTPUT
          fi
          if [[ "$new_version" =~ "520" ]]; then
            echo -e "ERROR: 599 -  - You must source this script when specifying an environment variable! Eg: '. ./foo.sh -e bar_ver'"
            exit 1 || true
          fi
          if [[ "$new_version" =~ "570" ]]; then
            echo -e "ERROR: 570 - Invalid argument!"
            exit 1 || true
          fi
          if [[ "$new_version" =~ "590" ]]; then
            echo -e "FATAL: 501 - This is not a git repository!"
            exit 1 || true
          fi
          if [[ "$new_version" =~ "591" ]]; then
            echo -e "ERROR: 591 - Unsupported origin host."
            exit 1 || true
          fi
          if [[ "$new_version" =~ "599" ]]; then
            echo -e "ERROR: 599 - No feature, enhancement, fix, bugfix, hotfix, or ops branches detected!"
            exit 1 || true
      shell: bash

# See github contexts for more like github.action_path.
# REF: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context