name: 'GitOps Automatic Versioning'
author: 'EvilKittenLord'
description: 'Automatically determine semantic version based on branch merge history.'
branding:
  icon: git-branch
  color: white
inputs:
  force-re-evaluate:
    description: "Forces a re-evaluation of the entire git history."
    required: false
    default: 'false'
outputs:
  new-version:
    description: "New Version"
    value: ${{ steps.new-version.outputs.new-version }}
  previous-version:
    description: "Previous Version"
    value: ${{ steps.previous-version.outputs.previous-version }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - id: new-version
      run: |
          opt=''
          [[ "${{ inputs.force-re-evaluate }}" == 'true' ]] && opt='-f'
          echo "new-version=$(${{ github.action_path }}/scripts/detectNewVersion.sh $opt)" >> $GITHUB_OUTPUT
      shell: bash
    - id: previous-version
      run: |
          echo "previous-version=$(${{ github.action_path }}/scripts/detectPreviousVersion.sh)" >> $GITHUB_OUTPUT
      shell: bash
