name: 'GitOps Automatic Versioning'
author: 'EvilKittenLord'
description: 'Automatically determine semantic version based on branch merge history.'
branding:
  icon: git-branch
  color: white
inputs:
  force-re-evaluate:
    description: "Forces a re-evaluation of the entire git history."
    required: false
    default: 'false'
outputs:
  new-version:
    description: "New Version"
    value: ${{ steps.new-version.outputs.new-version }}
  previous-version:
    description: "Previous Version"
    value: ${{ steps.previous-version.outputs.previous-version }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Ensure full commit history
      run: |
          cd $GITHUB_WORKSPACE
          git pull --unshallow
      shell: bash
    - name: Detect New Version
      id: new-version
      run: |
          cd $GITHUB_WORKSPACE
          opt=''
          [[ "${{ inputs.force-re-evaluate }}" == 'true' ]] && opt='-f'
          new_version="$(${{ github.action_path }}/scripts/detectNewVersion.sh $opt)"
          echo "new-version=$new_version" | tee $GITHUB_OUTPUT
          [[ "$o" =~ "ERROR" ]] && exit 1
      shell: bash
    - name: Detect Previous Version
      id: previous-version
      run: |
          cd $GITHUB_WORKSPACE
          echo "previous-version=$(${{ github.action_path }}/scripts/detectPreviousVersion.sh)" | tee $GITHUB_OUTPUT
      shell: bash

# See github contexts for more like github.action_path.
# REF: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context